name: build

on:
  push:
    branches:
      - master

jobs:
  build-base:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: 'master'
      - name: Test
        run: make test
      - name: Build
        run: make image
      - name: Push
        run: make push
        env:
          DOCKERHUB_USERNAME: gregthebunny
          DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
