name: Release
on:
  push:
    branches:
      - main

jobs:
  release:
    name: Tag and release new version
    runs-on: ubuntu-latest
    environment:
        name: release
    steps:
      - uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}

      - id: vars
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"

      - uses: SOLIDSoftworks/semver-tags@1.0.4
        id: semver
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          tag-prefix: "v"
          default-version: "0.0.1"

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build
        id: docker_build
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/webhug:${{ steps.semver.outputs.semantic-version }},${{ secrets.DOCKERHUB_USERNAME }}/webhug
          build-args: |
            "BUILD_COMMIT=${{ github.sha }}"
            "BUILD_VERSION=v${{ steps.semver.outputs.semantic-version }}"

      - name: Tag commit
        uses: tvdias/github-tagger@v0.0.2
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          tag: "${{ steps.semver.outputs.semantic-version }}"

      - name: Fetch tag
        uses: actions/checkout@v3
        with:
          ref: "v${{ steps.semver.outputs.semantic-version }}"
