name: Test
on:
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
        - uses: actions/setup-go@v5
          with:
              go-version: 1.19
        - uses: actions/checkout@v4
        - name: golangci-lint
          uses: golangci/golangci-lint-action@v6

  unit:
    name: Unit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Dependencies
        run: go mod download
      - name: Unit test
        run: go test --tags=unit -v -cover -race ./...

  build:
    name: Build
    needs:
      - lint
      - unit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build
        id: docker_build
        uses: docker/build-push-action@v6
        with:
          push: false
          tags: go-healthcheck:${{ github.sha }}
          build-args: |
            "BUILD_COMMIT=${{ github.sha }}"
