name: test

on:
  push:
    branches:
      - '**'
      - '!master'

jobs:
  build-base:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: "$GITHUB_REF"
      - name: Test
        run: make test

